name: Main Workflow

on: push

jobs:
  Upload-zipped-artifacts-to-s3-bucket:
    runs-on: ubuntu-latest
    steps:
      - run: echo "main workflow is triggered"

      - name: Make artifact directory
        run: mkdir -p ./artifacts/${{ github.repository }}

      - name: Create Zip File
        uses: montudor/action-zip@v0.1.0
        with:
        args: zip -r ./artifacts/${{ github.repository }}/${{ github.sha }}.zip ./src

      - name: Push Zip to S3
        uses: jakejarvis/s3-sync-action@v0.3.1
        env:
        SOURCE_DIR: "./artifacts"
        AWS_REGION: "ap-southeast-1"
        AWS_S3_BUCKET: "blk-44-buses-bot"
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
